services:
  pdfup:
    # simple mode - pdfup/pdfup-simple:latest
    # default mode - pdfup/pdfup:latest
    image: pdfup/pdfup-simple:latest
    container_name: pdfup
    restart: unless-stopped
    ports:
      - '8080:8080'
